# location of files for training
processed_dir_root: output/processed

# device to train on (gpu or cpu)
gpu: True

# model parameters
model: pointnet

# optimiser parameters
optimiser: adam
lr: 0.001
weight_decay: 0.0001

# training parameters
epochs: 2
batch_size: 1
num_workers: 1 # generall higher -> faster
loss_fn: nll
