# Mapping from integer labels to real terms
gt_label_map:
  0 : null # e.g. 0: background
  1 : null # e.g. 1: membrane

# When saving annotations - if true then localisations which are assigned a label of zero are not saved
drop_zero_label: False

# if using napari to annotate then the following applies
napari:
  # The number of bins in each dimension i.e. x_bins = 500, y_bins = 500 will create a
  # 500x500 pixel image - where the bin size in metric space will vary depending on the
  # input data
  x_bins: 500
  y_bins: 500
  z_bins: None

  # Dimensions of the data
  dim: 2 # Options: [2,3]


  # ----- ARCHIVED ARGUMENTS -------

  # Whether results should be plotted to screen (for anything/everything relevant)
  # plot: True

  # this defines the interpolation applied to the histogram when visualising the image of the histogram
  # - importantly the histogram which is part of dataitem will be kept in "raw form" i.e. underlying data unchaged
  # vis_interpolation: 'log2' # Options:
