# Mapping from integers to real terms
gt_label_map:
  0 : null # e.g. background
  1 : null # e.g. membrane
  
# When saving annotations - you can choose to not save the localisations which are assigned a label of zero
drop_zero_label: False

# if using napari to annotate then the following applies
napari:
  # The number of bins in each dimension i.e. x_bins = 500, y_bins = 500 will create a
  # 500x500 pixel image - where the bin size in metric space will vary depending on the
  # input data
  x_bins: 500
  y_bins: 500
  z_bins: None

  # Dimensions of the data either 2 or 3
  dim: 2

  # Whether plot should occur to screen (for anything/everything!)
  plot: True

  # this defines the interpolation applied to the histogram when visualising the image of the histogram
  # - importantly the histogram which is part of dataitem will be kept in "raw form"
  vis_interpolation: 'log2'




