# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternet

locclusternet:
  LocEncoderChannels: [[2, 4, 4, 4], [6, 6, 6, 6], [8, 8, 8, 8]]
  ClusterEncoderChannels: [[8, 18], [18, 24], [24, 32]]
  OutputChannels: 2
num_classes: 2

eval_on_gpu: True
