# configuration for feature analysis

# Options for what to analyse
pca_vs_convex_hull: True
boxplots: True
umap: False

# Features to analyse
features:
  - count
  - RGyration
  - linearity
  - planarity
  - length_pca
  - area_pca
  - density_pca
  - perimeter
  #- area_convex_hull
  #- length_convex_hull
  #- density_convex_hull

# sklearn parameters
log_reg:
  penalty: ["l1", "l2"]
  C: [0.1, 0.5, 1]
dec_tree:
  max_depth: [40, 45, 50]
  max_features: [4, 5, 6]
svm:
  C: [1]
  #'kernel':['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'],
  kernel: ["rbf"]
  gamma: ["scale"]  # , 'auto']
knn:
  n_neighbors: [3,5,7,9,11]
  weights: ["distance"]

label_map:
  fib: 0
  iso: 1
