files: ^src/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: [--maxkb=100]
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
#-   repo: https://github.com/pycqa/flake8
#    rev: 6.1.0
#    hooks:
#    -   id: flake8
#        args: [--ignore=E501]
#-   repo: https://github.com/pycqa/isort
#    rev: 5.12.0
#    hooks:
#    -   id: isort
#        name: isort (python)
#-   repo: https://github.com/econchick/interrogate
#    rev: 1.5.0  # or master if you're bold
#    hooks:
#    -   id: interrogate
#        args: [-v, --ignore-init-method, --fail-under=95]
-   repo: https://github.com/akaihola/darglint2
    rev: v1.8.2
    hooks:
    - id: darglint2
  