eval_on_gpu: true
label_level: graph
load_data_from_gpu: false
locclusternet:
  ClusterEncoderChannels: [[8, 18],[18, 24], [24, 32]]
  LocEncoderChannels:
  - - 2
    - 4
    - 4
    - 4
  - - 6
    - 6
    - 6
    - 6
  - - 8
    - 8
    - 8
    - 8
  OutputChannels: 2
model: locclusternet
num_classes: 2