# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternet

# parameters for the network
locclusternet:
  local_channels: [[2,16,32],[66,80,96]]
  global_channels: [[32,32,64],[96,96,128]]
  global_sa_channels: [130, 192, 256]
  final_channels: [256, 128, 8]
  ClusterEncoderChannels: [[8, 16, 16],[16,20,24],[24,28,32]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
