# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locnetonly_pointtransformer

# parameters for the network
locnetonly_pointtransformer:
  k: 16
  in_channels: 0
  out_channels: 8
  dim_model: [16, 32, 64]
  output_mlp_layers: 128
  ratio: 0.2
  pos_nn_layers: 54
  attn_nn_layers: 54

num_classes: 2

eval_on_gpu: True
