# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locnetonly_transformer

# parameters for the network
locnetonly_transformer:
  LocEncoderTransformer: [[1, 32, 2, 64, 64], [32, 64, 2, 128, 128], [64, 2, 2, 256, 256]]
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
