# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: clustermlp

# parameters for the network
clustermlp:
  channels: [8, 32, 128, 32, 2]
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
