# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locnetonly_pointtransformer

# parameters for the network
locnetonly_pointtransformer:
  k: 4
  in_channels: 0
  out_channels: 2
  dim_model: [16, 32, 64]
  output_mlp_layers: 128
  ratio: 1.0
  pos_nn_layers: 64
  attn_nn_layers: 64

num_classes: 2

eval_on_gpu: True
