# device to train on (gpu or cpu)
train_on_gpu: True
load_data_from_gpu: False

# model parameters
model: clustermlp

clustermlp:
  channels: [7, 32, 128, 32, 2]

# optimiser parameters
optimiser: adam
lr: 0.001
weight_decay: 0.0001

# training parameters
epochs: 50
batch_size: 2
num_workers: 1 # generall higher -> faster
loss_fn: nll

# what trying to predict
label_level: graph # graph

# train/val transforms
# options: ['normalisescale', 'jitter', 'flip', 'randscale', 'rotate', 'subsample', 'shear'] # null
transforms: 
  z_rotate: null
  # 1 unit in new space ~= max(fov_x, fov_y)/2 - it will differ slightly as data itself might not cover full fov range
  # fov_x/fov_y is defined in process.yaml
  # here 1 unit = 20,000nm
  # therefore 15nm = 0.00075 units
  jitter: 0.00075
  x_flip: null
  y_flip: null 
  randscale: [0.95,1.05]
  shear: 0.05
  # subsample

# wandb parameters
wandb_project: semore_task4
wandb_dataset: semore