batch_size: 2
clustermlp:
  channels:
  - 7
  - 32
  - 128
  - 32
  - 2
epochs: 50
label_level: graph
load_data_from_gpu: false
loss_fn: nll
lr: 0.001
model: clustermlp
num_workers: 1
optimiser: adam
train_on_gpu: true
transforms:
  jitter: 0.00075
  randscale:
  - 0.95
  - 1.05
  shear: 0.05
  x_flip: null
  y_flip: null
  z_rotate: null
wandb_dataset: semore
wandb_project: semore_task4
weight_decay: 0.0001
