# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternettransformer

# parameters for the network
locclusternettransformer:
  # locnet
  k: 4
  in_channels: 0
  out_channels: 8
  dim_model: [16, 32, 64]
  output_mlp_layers: 128
  ratio: 1.0
  pos_nn_layers: 64
  attn_nn_layers: 64
  # clusterencoder
  ClusterEncoderChannels: [[16, 16, 16],[16,20,24],[24,28,32]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
