# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locnetonly_pointnet

# parameters for the network
locnetonly_pointnet:
  LocEncoderChannels_local: [[2, 8], [18, 32], [34, 64]]
  LocEncoderChannels_global: [[8, 16], [32, 32], [64, 2]]
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
