# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternet

# parameters for the network
locclusternet:
  local_channels: [[2, 32, 32, 64],[130, 64, 64, 128]]
  global_channels: [[64, 128, 128],[128, 256, 256]]
  global_sa_channels: [258, 128, 128, 128]
  final_channels: [128, 64, 32, 8]
  dropout: 0.0
  ratio: 1.0
  radius: 1.0
  k: 4
  conv_type: gin
  add_cluster_pos: True
  ClusterEncoderChannels: [[18, 16, 16],[18,20,24],[26,28,32]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
