# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: [CHANGE]

# parameters for the network
[CHANGE]:
  [CHANGE]

num_classes: 2

eval_on_gpu: True
