# configuration for feature analysis

# sklearn parameters
log_reg:
  penalty: [CHANGE]
  C: [CHANGE]
dec_tree:
  max_depth: [CHANGE]
  max_features: [CHANGE]
#svm:
#  C: 1
#  kernel: [CHANGE] "rbf"
#  gamma: "scale"  # , 'auto']
knn:
  n_neighbors: [CHANGE]
  weights: [CHANGE]

label_map:
  fib: 0
  iso: 1

# if nn_feat
nn_feat:
  dim: 2
  locclusternet:
    ClusterEncoderChannels: [[8, 16],[16, 24], [24, 32]]
    LocEncoderChannels_local: [[2, 8], [18, 24], [18, 8]]
    LocEncoderChannels_global: [[8, 16], [24, 16], [8, 8]]
    OutputChannels: 2
    dropout: 0.0
  model: locclusternet
  fold: 0
  # find the model name from weights&bias for the corresponding fold
  model_name: INSERTMODELNAME.pt
  device: gpu
