# plot pca length/area vs convex hull to compare
pca_vs_convex_hull: False
# plot features to screen (features will be saved regardless)
boxplots: True
# run umap on the features
umap: True
# run kmeans on the features
kmeans: True
# run pca on the data
pca:
  # if implement True will run PCA
  implement: True
  # number of compoments to retain during PCA
  n_components: 2

# map from real terms to the integer labels
label_map:
  fib: 0
  iso: 1

# Features to analyse (below are entire list that can be selected)
features:
  - count
  - RGyration
  - linearity
  - planarity
  - length_pca
  - area_pca
  - density_pca
  - perimeter
  #- area_convex_hull
  #- length_convex_hull
  #- density_convex_hull

# if specified then logistic regression applied to features
log_reg:
  # penalties to evaluate
  logistic__penalty: [CHANGE]
  # inverse of regularisation strength
  logistic__C: [CHANGE]

# if specified then decision tree applied to features
dec_tree:
  # depth of tree
  tree__max_depth: [CHANGE]
  # number features to consider
  tree__max_features: [CHANGE]

# if specified then svm applied to features
svm:
  # regularisation parameter
  svm__C: [CHANGE]
  #'kernel used
  svm__kernel: [CHANGE]
  # kernel coefficient
  svm__gamma: [CHANGE]

# if specified then knn applied to features
knn:
  # number of neighbours
  knn__n_neighbors: [CHANGE]
  # weight function used during prediction
  knn__weights: [CHANGE]
