# map from real terms to the integer labels
label_map:
  fib: 0
  iso: 1

# whether to run on gpu or cpu
device: gpu # Options: [cpu, gpu]

# choice of model
model: locclusternet # Options: see train.yaml

# if automatic flag not specified then load in specific model name
# the name of the model can be found from weights&bias for the corresponding fold
model_name: INSERTMODELNAME.pt

# parameters for the network
[change]:
  [change]

# ---- Explainable AI arguments -----

# if specified then run through pgexplainer
pgex:
  # size regularization to constrain the explanation size
  edge_size: 0.00000001
  # entropy regularization to constrain the connectivity of explanation
  edge_ent: 0.00000001
  # maximum number of networks to train explanation network
  max_epochs: 20
  # learning rate during training of explanation network
  lr: 0.003
  # batch size during training of explanation network
  batch_size: 128
  # each value in the the edge mask is divided by temperature
  # i.e. lower temperature more confidence vs higher temperature
  # more spread out confidence in masks
  # where temperature is given by
  # temp[0] * (temp[1]/temp[0])^ (epoch/total_epochs)
  # i.e. at low epochs closer to temp[0]
  # and at high epochs closer to temp[1]
  # since temp[0] > temp[1]
  # at low epochs higher temp, at high epochs lower temp
  # i.e. start with more uniform sampling towards spikier sampling
  temp: [5.0,2.0]
  # bias - parameter for sampling
  bias: 0.0
