eval_on_gpu: true
label_level: graph
load_data_from_gpu: false
locclusternet:
  ClusterEncoderChannels:
  - - 15
    - 20
    - 25
  - - 25
    - 25
    - 25
  - - 25
    - 28
    - 32
  LocEncoderChannels:
  - - 2
    - 4
    - 4
    - 4
  - - 6
    - 6
    - 6
    - 6
  - - 8
    - 8
    - 8
    - 8
  OutputChannels: 2
model: locclusternet
num_classes: 2
pgex:
  coeff_ent: 1.0e-08
  coeff_size: 1.0e-08
  emb_layer_name: cluster_encoder_2
  explain_graph: true
  lr: 0.1
  max_epochs: 50
wandb_dataset: semore
wandb_project: semore_task2
