batch_size: 2
epochs: 100
label_level: graph
load_data_from_gpu: false
locclusternet:
  ClusterEncoderChannels:
  - 15
  - 18
  - 24
  - 32
  LocEncoderChannels:
  - - 2
    - 4
    - 4
    - 4
  - - 6
    - 6
    - 6
    - 6
  - - 8
    - 8
    - 8
    - 8
  OutputChannels: 2
loss_fn: nll
lr: 0.001
model: locclusternet
num_workers: 1
optimiser: adam
train_on_gpu: true
transforms:
  jitter: 0.00075
  randscale:
  - 0.95
  - 1.05
  shear: 0.05
  x_flip: null
  y_flip: null
  z_rotate: null
wandb_dataset: semore
wandb_project: semore_task2
weight_decay: 0.0001
