# map from real terms to the integer labels
label_map:
  one: 0
  two: 1
  three: 2
  T: 3
  O: 4
  L: 5
  grid: 6

# Features to analyse (below are entire list that can be selected)
features:
  - count
  - RGyration
  - linearity
  - planarity
  - length_pca
  - area_pca
  - density_pca
  - perimeter
  #- area_convex_hull
  #- length_convex_hull
  #- density_convex_hull
