# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: clusternet

# parameters for the network
clusternet:
  ClusterEncoderChannels: [[8, 16],[16, 24], [24, 32]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
