# whether to load the data directly from the gpu
load_data_from_gpu: False

# whether making node or whole graph predictions
label_level: graph # Options: [node, graph]

# number of classes in the dataset
num_classes: 2

# whether to evaluate on the gpu
eval_on_gpu: True

# choice of model
model: clusternet # Options: see below

# parameters for the network
clusternet:


  # +++++ ClusterNet parameters +++++
  # Dropout for each layer during evaluate should be 0.0
  dropout: 0.0 # CAREFUL CHANGING!
  cluster_conv_type: pointtransformer # Options: [gin, transformer, pointnet, pointtransformer]
  # number of final output channels
  OutputChannels: 2
  # add position coordinates to each cluster
  add_cluster_pos: False

  # --- if cluster_conv_type == pointtransformer ------------
  # input channel size for each layer
  pt_tr_in_channels: [8, 16, 24, 32]
  # output channel size for each layer
  pt_tr_out_channels: [16, 24, 32, 40]
  # size of hidden channel for position NN
  pt_tr_pos_nn_layers: 32
  # size of hidden channel for attention NN
  pt_tr_attn_nn_layers: 32
  # dimensions of data: options = [2,3]
  pt_tr_dim: 2
  # -------------------------------------------------
