# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternet

# parameters for the network
locclusternet:
  local_channels: [[2, 32, 32, 64],[130, 64, 64, 128]]
  global_channels: [[64, 128, 128],[128, 256, 256]]
  global_sa_channels: [258, 128, 128, 128]
  final_channels: [128, 64, 32, 8]
  dropout: 0.0 # was 0.5
  ratio: 1.0
  radius: 1.0
  k: 4
  conv_type: transformer
  ClusterEncoderOutChannels: [16, 24, 32]
  heads: 1
  concat: True
  beta: False
  OutputChannels: 2

num_classes: 2

eval_on_gpu: True
