# configuration for feature analysis

pca_vs_convex_hull: False
boxplots: False
umap: False
kmeans: True
pca: 
  implement: True
  n_components: 3

# sklearn parameters
log_reg:
  penalty: ["l1", "l2"]
  C: [0.1, 0.5, 1]
dec_tree:
  max_depth: [40, 45, 50]
  max_features: [4, 5, 6]
svm:
  C: [1]
  #'kernel':['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'],
  kernel: ["rbf"]
  gamma: ["scale"]  # , 'auto']
knn:
  n_neighbors: [3]
  weights": ["distance"]

features:
  - count
  - RGyration
  - linearity
  - planarity
  - length_pca
  - area_pca
  - density_pca
  - perimeter

label_map:
  fib: 0
  iso: 1
