# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locnetonly_pointnet

# parameters for the network
locnetonly_pointnet:
  local_channels: [[2,16,32],[66,80,96]]
  global_channels: [[32,32,64],[96,96,128]]
  global_sa_channels: [130, 192, 256]
  final_channels: [256, 128, 2]
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
