# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternettransformer

# parameters
locclusternettransformer:
  # locnet
  k: 16
  in_channels: 0
  out_channels: 8
  dim_model: [16, 32, 64]
  output_mlp_layers: 128
  ratio: 0.2
  pos_nn_layers: 54
  attn_nn_layers: 54
  # clusterencoder
  ClusterEncoderChannels: [[16, 16],[16, 24], [24, 32]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
