# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternettransformer

# parameters for the network
locclusternettransformer:
  # LocEncoderTransformer: [input_channels, output_channels, dimensions, posn_nn_channels, attention_nn_channels]
  LocEncoderTransformer: [[1, 8, 2, 32, 32], [8, 16, 2, 32, 32], [16, 8, 2, 32, 32]]
  ClusterEncoderChannels: [[8, 8],[8, 8], [8, 8]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
