# train/test/val ratio splits only specify it not using k-fold
# train_ratio: 0.7
# val_ratio: 0.15
# test_ratio: 0.15

# this argument is redundant but has to be specified for the moment
save_on_gpu: False

# what dimensions to load into position data
pos: xy # Options: [xy, xyz]

# per localisation features
# null -> no localisation features considered
# e.g. ["photons", "error"] -> features present in original dataset for each localisation to consider
loc_feat: null # Options: null OR list of features
# per cluster features
# null -> no cluster features considered
# e.g. to consider all features
#  cluster_feat:
#   - count
#   - RGyration
#   - linearity
#   - planarity
#   - length_pca
#   - area_pca
#   - perimeter
#   - density_pca
cluster_feat: null

# whether making node or whole graph predictions
label_level: graph # Options: [node, graph]

# type of model
model: ClusterLoc # Options: [ClusterLoc] Future: Build support for [Loc, Cluster]

# number of nearest neighbours to connect clusters to in graph
kneighboursclusters: 3

# number of nearest neighbours to connect locs to in graph
# note localisations are only connected to other localisations in the same cluster
# if null then connects all locs within each cluster
# note if using PointNet or PointTransformer - these connections are not used!
kneighbourslocs: 3

# size of fov in x/y in original units e.g. nm
fov_x: 40000.0
fov_y: 40000.0

# ---- Archived arguments ------

# whether to save to gpu
# save_on_gpu: False
