# configuration for feature analysis

# Options for what to analyse
pca_vs_convex_hull: False
boxplots: False
umap: False

# Features to analyse
features:
  - count
  - RGyration
  - linearity
  - planarity
  - length_pca
  - area_pca
  - density_pca
  - perimeter
  #- area_convex_hull
  #- length_convex_hull
  #- density_convex_hull

# sklearn parameters
log_reg:
  penalty: ["l1", "l2"]
  C: [0.01, 0.1, 1]
dec_tree:
  max_depth: [10, 20, 30]
  max_features: [3, 5, 8]
#svm:
#  C: [1]
#  #'kernel':['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'],
#  kernel: ["rbf"]
#  gamma: ["scale"]  # , 'auto']
knn:
  n_neighbors: [10, 20, 30]
  weights: ["distance"]


label_map:
  normal: 0
  cancer: 1

# if nn_feat
nn_feat:
  dim: 2
  locclusternet:
    ClusterEncoderChannels: [[8, 16],[16, 24], [24, 32]]
    LocEncoderChannels_local: [[2, 8], [18, 24], [18, 8]]
    LocEncoderChannels_global: [[8, 16], [24, 16], [8, 8]]
    OutputChannels: 2
    dropout: 0.0
  model: locclusternet
  fold: 0
  # find the model name from weights&bias for the corresponding fold
  model_name: task_1_semore_dataset_1_17:41_11:1:2024_.pt
  device: gpu