# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternet

# parameters for the network
locclusternet:
  ClusterEncoderChannels: [[16, 16],[16, 24], [24, 32]]
  LocEncoderChannels_local: [[2, 8], [18, 32], [66, 32]]
  LocEncoderChannels_global: [[8, 16], [32, 64], [32, 8]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
