# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

# model parameters
model: locclusternet

# parameters for the network
locclusternet:
  local_channels: [[2,64],[66,128]]
  global_channels: [[64,64],[128,128]]
  global_sa_channels: [130, 256]
  final_channels: [256, 8]
  ClusterEncoderChannels: [[16, 16],[16, 24], [24, 32]]
  OutputChannels: 2
  dropout: 0.0

num_classes: 2

eval_on_gpu: True
