# params
load_data_from_gpu: False

# what trying to predict
label_level: graph # graph

model: clusternet
clusternet:
  # Dropout for each layer
  dropout: 0.0
  # +++++ ClusterNet parameters +++++
  conv_type: gin # Options: [gin, transformer]
  # number of final output channels
  OutputChannels: 2
  # add position coordinates to each cluster
  add_cluster_pos: True
  # --- if conv_type == gin ------------
  ClusterEncoderChannels: [[10, 16, 16],[18,20,24],[26,28,32]]
  # ------------------------------------

num_classes: 2

eval_on_gpu: True
