# The following are the names of the
# x column, y column, z column if present, channel, frame,
# in the parquet files being processed
x_col: '# x[nm]'
y_col: 'y[nm]'
z_col: null
channel_col: 'channelIndex[]'
frame_col: 'frameIndex[]'

# The number of dimensions to consider
# If 2 only deals with x and y
# If 3 will read in and deal with z as well (currently not fully supported)
dim: 2

# choice of which channels user wants to consider
# if null considers all
channel_choice: [0]

# specify string for each channel
channel_label:
  0: EREG

# whether to not drop the column containing
# pixel
drop_pixel_col: False

# files to include: all for everyone
include_files: all
  #- file_1
  #- file_2

## Choice of input features
features: []

## GT label per loc OR fov
gt_label_scope: fov

# if gt_label_scope is 'loc' then the following applies
gt_label_loc:
  gt_label_map:
    0 : null
    1 : null
  # which column is the gt label in
  gt_label_col : null

# if gt_label_scope is 'fov' then we assume
# but will check that gt_label and gt_label_map are both
# in the metadata
