name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
      - name: Set up first environment
        run: |
          micromamba create -n locpix-points -c conda-forge python=3.11
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate locpix-points
          pip install .
          git clone https://github.com/oubino/DIG
          cd DIG
          pip install .
          cd ..
          git clone https://github.com/oubino/pytorch_geometric.git
          cd pytorch_geometric
          pip install -e .
          git checkout hetero_transforms
          cd ..
          pip install open3d torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cu121.html torch-sparse -f https://data.pyg.org/whl/torch-2.1.0+cu121.html torch-cluster -f https://data.pyg.org/whl/torch-2.1.0+cu121.html torch-summary torchmetrics pytest --no-cache-dir
      - name: Test
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate locpix-points
          cd locpix_points/demo
          initialise
      # continue from here

      #- name: Test with tox
      #  run: tox
      #- name: Add .env file to allow subsequent steps
      #  run: |
      #    touch .env
      #    echo 'RAW_DATA_PATH = tests/test_data' >> .env
      #- name: Install requirements
      #  run: |
      #    make requirements
      #- name: Install tox dependencies
      #  run: |
      #    python -m pip install tox-gh-actions
      #- name: Test with tox
      #  run: tox
      #- name: Lint with flake8
      #  run: |
      #    # stop the build if there are Python syntax errors or undefined names
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
