splits:
  test:
  - - piccolo_tma4_9_11_23_I6_P256_T2_FOV3.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV4.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV4.parquet
    - piccolo_tma2_13_10_23_C2_P65_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV3.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV2.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV4.parquet
  - - piccolo_tma5_27_10_23_G10_P320_T2_FOV3.parquet
    - piccolo_tma5_19_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma5_19_10_23_F6_P314_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV2.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV2.parquet
    - piccolo_tma5_19_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV4.parquet
  - - piccolo_tma5_27_10_23_G10_P320_T2_FOV2.parquet
    - piccolo_tma2_12_10_23_G5_P92_T1_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma5_19_10_23_J2_P336_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV2.parquet
    - piccolo_tma5_19_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV2.parquet
  - - piccolo_tma5_26_10_23_J1_P336_T1_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV3.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV1.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV3.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV2.parquet
  - - piccolo_tma4_9_11_23_I3_P254_T3_FOV4.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV4.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV2.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV2.parquet
    - piccolo_tma2_13_10_23_E3_P78_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV4.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV1.parquet
  train:
  - - piccolo_tma4_9_11_23_J5_P261_T1_FOV2.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV1.parquet
    - piccolo_tma2_13_10_23_E3_P78_T3_FOV1.parquet
    - piccolo_tma5_19_10_23_J2_P336_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV4.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV3.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV3.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV4.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma5_19_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma5_19_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV2.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV2.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV2.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV1.parquet
    - piccolo_tma2_12_10_23_G5_P92_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV2.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV2.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV3.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV4.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV2.parquet
  - - piccolo_tma4_9_11_23_H2_P246_T2_FOV3.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV2.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV2.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV2.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV2.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV2.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV2.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV3.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV3.parquet
    - piccolo_tma5_19_10_23_J2_P336_T2_FOV1.parquet
    - piccolo_tma2_12_10_23_G5_P92_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV4.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV3.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV4.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV2.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV3.parquet
    - piccolo_tma2_13_10_23_C2_P65_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV3.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV1.parquet
    - piccolo_tma5_19_10_23_F3_P313_T3_FOV1.parquet
  - - piccolo_tma4_9_11_23_I3_P254_T3_FOV2.parquet
    - piccolo_tma2_13_10_23_E3_P78_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV2.parquet
    - piccolo_tma5_19_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV4.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV2.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV3.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV3.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV2.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV4.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV4.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV2.parquet
    - piccolo_tma5_19_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV2.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV1.parquet
    - piccolo_tma2_13_10_23_C2_P65_T2_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV3.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV4.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV3.parquet
  - - piccolo_tma5_19_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_19_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV3.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV2.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV2.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV2.parquet
    - piccolo_tma5_19_10_23_F6_P314_T2_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV2.parquet
    - piccolo_tma5_19_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV2.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV3.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV4.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV4.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV4.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV4.parquet
    - piccolo_tma2_13_10_23_C2_P65_T2_FOV1.parquet
    - piccolo_tma2_13_10_23_E3_P78_T3_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV3.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV4.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV2.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV3.parquet
  - - piccolo_tma5_26_10_23_J1_P336_T1_FOV2.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV2.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV3.parquet
    - piccolo_tma5_19_10_23_J2_P336_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV2.parquet
    - piccolo_tma5_19_10_23_J3_P336_T3_FOV2.parquet
    - piccolo_tma2_13_10_23_C2_P65_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV4.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV1.parquet
    - piccolo_tma5_19_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV3.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV3.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV4.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV2.parquet
    - piccolo_tma5_19_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV2.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma5_19_10_23_F3_P313_T3_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV3.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV2.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV1.parquet
  val:
  - - piccolo_tma5_27_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_19_10_23_G10_P320_T2_FOV1.parquet
    - piccolo_tma5_19_10_23_F6_P314_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV4.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV3.parquet
    - piccolo_tma4_9_11_23_J5_P261_T1_FOV3.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV2.parquet
  - - piccolo_tma5_26_10_23_J7_P339_T3_FOV1.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV4.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV4.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV4.parquet
    - piccolo_tma2_13_10_23_E3_P78_T3_FOV1.parquet
    - piccolo_tma4_9_11_23_I3_P254_T3_FOV4.parquet
  - - piccolo_tma5_27_10_23_F3_P313_T3_FOV3.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV4.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV4.parquet
    - piccolo_tma5_27_10_23_G10_P320_T2_FOV4.parquet
    - piccolo_tma5_19_10_23_F6_P314_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV3.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV3.parquet
  - - piccolo_tma5_19_10_23_J2_P336_T2_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV4.parquet
    - piccolo_tma2_12_10_23_G5_P92_T1_FOV1.parquet
    - piccolo_tma5_27_10_23_F3_P313_T3_FOV2.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV2.parquet
    - piccolo_tma4_9_11_23_H2_P246_T2_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV4.parquet
  - - piccolo_tma4_9_11_23_I6_P256_T2_FOV4.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV1.parquet
    - piccolo_tma5_26_10_23_J1_P336_T1_FOV3.parquet
    - piccolo_tma5_26_10_23_J7_P339_T3_FOV4.parquet
    - piccolo_tma5_19_10_23_F6_P314_T2_FOV1.parquet
    - piccolo_tma2_12_10_23_G5_P92_T1_FOV1.parquet
    - piccolo_tma4_9_11_23_I6_P256_T2_FOV3.parquet
