# device to train on (gpu or cpu)
train_on_gpu: True
load_data_from_gpu: False

# model parameters
model: clustermlp

# parameters for the network
clustermlp:
  channels: [8, 16, 24, 32, 2]
  dropout: 0.0

# optimiser parameters
optimiser: adam
lr: 0.001
weight_decay: 0.0001

# training parameters
epochs: 100
batch_size: 2
num_workers: 1 # generall higher -> faster
loss_fn: nll

# whether to sample imbalanced i.e. oversample from minority class/undersample from majority
imbalanced_sampler: True

# what trying to predict
label_level: graph # node

# train/val transforms
transforms:
  # 1 unit in new space ~= max(fov_x, fov_y)/2 - it will differ slightly as data itself might not cover full fov range
  # fov_x/fov_y is defined in process.yaml
  # here 1 unit = 40,000nm
  # therefore 15nm = 0.000375 units
  jitter: 0.000375 # number of nm
  randscale: [0.95,1.05]
  shear: 0.05
  x_flip: null
  y_flip: null
  z_rotate: null
